# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNpjm5pBIqsLTpD1xelR9IoEB5LAxuaI
"""



kullanici= []
kullanici.append(input("ad:"))
kullanici.append(input("soyad:"))
kullanici.append(int(input("yas:")))
kullanici.append(int(input("dogum yili:")))

for i in range(3):
  print(kullanici[i])
if kullanici[2] < 18:
  print("DIŞARI ÇIKAMAZSINIZ. TEHLİKELİ")
else: 
  print("DIŞARI ÇIKABİLİRSİNİZ.")

