# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNpjm5pBIqsLTpD1xelR9IoEB5LAxuaI
"""

deger=[]
for i in range(5):
    deger.append(input("deger giriniz"))
    print(f"degeriniz: {deger[i]} ve type: {type(deger[i])}")