# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKeSNhok7gQruR7w63FlJZq-R1sl1tgG
"""

ad= "bugra"
soyad= "sonmez"
t=0
for i in range(4):
  s=input("adınızı ve soyadınızı giriniz:")
  t= t + 1
  if s == ad +" "+ soyad:
    print("hos geldiniz.")
    break
  elif t >= 3:
    print("daha sonra tekrar deneyiniz.")
    break
dersler= []
k = int(input("kaç ders almak istiyorsunuz?(en az 3 en fazla 5 ders alabilirsiniz) "))
for i in range(k):
  if k < 3:
    print("Basarısız oldunuz.")
    break
  elif k >5:
    print("maksimum 5 ders secebilirsiniz.")
    break
  elif k >= 3 and k <= 5:  
    ders = input("ders adı giriniz:")
    dersler.append(ders)
  elif i == k:
    break 
print(dersler)
ders_dict = {}
len(dersler)
for each in range(len(dersler)):
  ders_dict[each] = dersler[each]
print(ders_dict)
notlar = {}
notlar["ara sınav"] = "%30"
notlar["final"] = "%50"
notlar["proje"] = "%20"
print(notlar)

for i in range(len(dersler)):
  d = input("SINAV İÇİN BİR DERS İSMİ GİRİN")
  if d == dersler[i]:
    print("ara sınavınız: 38, final: 66, proje: 89")
    ortalama = (38+66+89)/3
    print("ortalamanız: ", ortalama)
    break
    if ortalama < 30:
        print("harf notunuz: FF")
        print("dersi geçemediniz")
    elif ortalama >= 30 and ortalama < 50:
        print("harf notunuz: DD")
    elif ortalama >= 50 and ortalama < 70:
        print("harf notunuz: CC")
    elif ortalama >= 70 and ortalama < 90:
        print("harf notunuz: BB")
    elif ortalama >= 90:
        print("harf notunuz: AA")
    else :
        print("ders adı doğru girilmedi.")

